import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NAV_ITEMS, NAV_ITEMS_CTA } from "@/constants";
import Link from "next/link";
import { ButtonAsChild } from "@/components/ButtonAsChild";
import { buttonVariants } from "@/components/ui/button";
import NextImage from "next/image";
import { ButtonLink } from "@/components/ButtonLink";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased text-primary-foreground max-w-7xl md:container mx-auto`}
        >
          <header className="w-full flex justify-between py-8">
            <figure className="flex items-center">
              <Link href="/">
                <NextImage
                  src="/images/brand-logo.svg"
                  width={132}
                  height={32}
                  alt="get_hired logo"
                />
              </Link>
              <h1 className="sr-only">LOGO</h1>
            </figure>
            <nav className="flex gap-8 justify-between items-center">
              <ul className="flex gap-4">
                {NAV_ITEMS.map(({ id, label, href }) => (
                  <li key={id}>
                    <Link href={href}>{label}</Link>
                  </li>
                ))}
              </ul>
              <ul className="flex gap-2">
                <li className="">
                  <Link
                    href="/sign-in"
                    className={buttonVariants({ variant: "outline" })}
                  >
                    Log in
                  </Link>
                </li>
                <li>
                  <Link
                    href="/get-started"
                    className={`${buttonVariants({
                      variant: "default",
                    })} bg-primary text-primary-foreground hover:bg-primary/80`}
                  >
                    Get started
                  </Link>
                </li>
              </ul>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
