import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NAV_ITEMS, NAV_ITEMS_CTA } from "@/constants";
import Link from "next/link";
import { ButtonAsChild } from "@/components/ButtonAsChild";
import { buttonVariants } from "@/components/ui/button";
import NextImage from "next/image";
import { ButtonLink } from "@/components/ButtonLink";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased text-primary-foreground max-w-7xl md:container mx-auto`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
