services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=IsThisReallySecret
      - POSTGRES_USER=hire_me
      - POSTGRES_DB=hire_me_db
    networks:
      - hiremenetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hire_me", "-d", "hire_me_db"]

volumes:
  postgres_data:
    driver: local

networks:
  hiremenetwork:
    driver: bridge
