spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hire_me_db
    username: hire_me
    password: IsThisReallySecretIDontThinkSoLol
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





