spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hire_me_db
    username: hire_me
    password: IsThisReallySecretIDontThinkSoLol
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


