#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/hire_me_db
#    username: hire_me
#    password: IsThisReallySecretIDontThinkSoLol
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true

logging:
  level:
    root: DEBUG



